eureka:
  client:
    service-url:
      default-Zone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
server:
  port: 2222
  
spring:
  application:
    name: STOCK-PRICE-API
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: stockMarket
    password: root
    url: jdbc:mysql://localhost:3306/stockMarket
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect   
    
     
