eureka:
  client:
    service-url:
      default-Zone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
server:
  port: 3333
   
spring:
  application:
    name: STOCK-CALCULATION-SERVICE
   
    


        