server:
  port: 4444
  
eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/ 
      
spring:
  application:
    name: STOCK-FOR-API-GATEWAY 
  cloud:
      gateway:
        routes:
           - id: STOCK-PRICE-API
             uri: lb://STOCK-PRICE-API
             predicates:
                  - Path=/price/{comapnyName}
           - id: STOCK-CALCULATION-SERVICE
             uri: lb://STOCK-CALCULATION-SERVICE
             predicates:
                  - Path=/cal/{comapnyName}/{quantity}
    
    
    
    
    