server:
  port: 5678
  
  
eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_URL:http://localhost:9090}/eureka/ 
      
spring:
  application:
    name: API-GATEWAY 
  cloud:
      gateway:
        routes:
           - id: DOCTOR-DETAILS
             uri: lb://DOCTOR-DETAILS
             predicates:
                  - Path=/doctor
           - id: PATIENT-DETAILS
             uri: lb://PATIENT-DETAILS
             predicates:
                  - Path=/patient
    
    
    
    
    
    
    